sudo: required

language: scala

branches:
  only:
    - master
services:
  - docker
before_install:
  - docker run -d -p 8888:8888 r3v3r/ssdb
before_script:
  - sleep 15
scala:
  - 2.11.8

jdk:
  - oraclejdk8